### ISSUE TITLE
[Feature] Understanding Snowflake and tmp view models

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_hubspot_source#116]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Continuing discussions from [this slack thread ](https://getdbt.slack.com/archives/C01D1R2JLLA/p1696244522296389)and [this one](https://fivetran.slack.com/archives/C02919TN9AT/p1685694989192809), this issue is for a deeper investigation into this. 

The problem arises in Snowflake when a source's dimensions changes, but the dbt model has been run again. 

The proposed solution is to update our `tmp` view models is to use `dbt_utils.star` at least for Snowflake targets.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by reubster** [comment]
"The problem arises in Snowflake when a source's dimensions changes, but the dbt model has **not yet** been run again."

@fivetran-catfritz .. responding to your Slack question; 

"In Snowflake, are you also persisting docs, or does this happen regardless?"

Went to look up what you meant by "persisting docs". I didn't know that was a feature in dbt. No, we're not using it. 

When I look at the view definition in Snowflake, Snowflake has 'materialised' the column names of the view... but still has the same select * from body. 

Seems a straightforward fix to itemise the columns at dbt-run using dbt_utils.star

<img width="1399" alt="image" src="https://github.com/fivetran/dbt_hubspot_source/assets/19515061/9c5101fc-3235-4da8-9ea2-23595cac70cc">

**Comment by fivetran-joemarkiewicz** [comment]
Hi @reubster I would agree with you that we can ideally solve this with a dbt_utils.star in the tmp models.

My team is planning to pick this up for hubspot in the coming sprint (starting 10/18). However, if you need an immediate fix for this I noticed you are open to creating a PR. If you would like to open a PR I would be more than happy to review your PR and integrate your changes into the next release of the HubSpot package!
