### ISSUE TITLE
[Bug] stg_hubspot__contact:  Duplication between PROPERTY_CREATEDATE and PROPERTY_CREATED_AT

### ISSUE THREAD

**Issue by moreaupascal56** [fivetran/dbt_hubspot_source#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hello,

I have an issue with a duplicate column, when running `dbt run -s +stg_hubspot_contact` I have the following error 
![Capture d’écran 2023-10-11 à 10 47 18](https://github.com/fivetran/dbt_hubspot_source/assets/50910271/ccd7a074-85db-421b-a388-b96b47f15fb8)

I have   `hubspot__pass_through_all_columns: true`

I had a closer look and it seems that the properties: PROPERTY_CREATEDATE and PROPERTY_CREATED_AT are named after prefix removal PROPERTY_CREATED_AT. 

I think this is because in [get_contact_columns() macro
](https://github.com/fivetran/dbt_hubspot_source/blob/main/macros/get_contact_columns.sql) the PROPERTY_CREATEDATE is mapped to `created_at`: 
`    {"name": "property_createdate", "datatype": dbt.type_timestamp(), "alias": "created_at"},
`

The issue comes from the fact that the column PROPERTY_CREATED_AT is not excluded in the exclude parameter of [stg_hubspot__contact](https://github.com/fivetran/dbt_hubspot_source/blob/b79137d6bc79087dac779020cf800868aa2e027e/models/stg_hubspot__contact.sql#L35) which only returns these columns:

```
['_FIVETRAN_DELETED', '_FIVETRAN_SYNCED', 'ID', 'PROPERTY_HS_CALCULATED_MERGED_VIDS', 'PROPERTY_EMAIL', 'PROPERTY_COMPANY', 'PROPERTY_FIRSTNAME', 'PROPERTY_LASTNAME', 'PROPERTY_CREATEDATE', 'PROPERTY_JOBTITLE', 'PROPERTY_ANNUALREVENUE']

```

(so PROPERTY_CREATEDATE and not PROPERTY_CREATED_AT)

And then obviously PROPERTY_CREATED_AT is renamed as created_at and this is causing the issue. 
Hope I was clear enough

Have a great day

### Relevant error log or model output

```shell
see above
```

### Expected behavior

Either exclude PROPERTY_CREATED_AT by default to avoid this issue or change  PROPERTY_CREATEDATE mapping
I think the PROPERTY_ + aliases defined in  [get_contact_columns() macro
](https://github.com/fivetran/dbt_hubspot_source/blob/main/macros/get_contact_columns.sql) should be excluded as well. 

### dbt Project configurations

dbt hubspot source 0.12.0
dbt 1.4.4

### Package versions

dbt hubspot source 0.12.0
dbt 1.4.4

### What database are you using dbt with?

snowflake

### dbt Version

dbt 1.4.4

### Additional Context

maybe we will open a PR 

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by moreaupascal56** [comment]
I created this attached PR to showcase the issue but I guess there is better way to fix it

**Comment by fivetran-catfritz** [comment]
Hi @moreaupascal56 thanks for flagging this issue! I have started taking a look at this and could use a little more information. In your source `contact` table, are you seeing both `PROPERTY_CREATEDATE` and `PROPERTY_CREATED_AT ` columns, or only `PROPERTY_CREATED_AT`?

**Comment by moreaupascal56** [comment]
Hey thanks !  we have both columns in the source table. I don't know
however if this is a custom property we made on hubspot or a default one
from hubspot

Le mer. 11 oct. 2023, 21:27, fivetran-catfritz ***@***.***> a
écrit :

**Comment by fivetran-catfritz** [comment]
@moreaupascal56 Thank you much for the info! I will discuss this with our internal team.

**Comment by fivetran-catfritz** [comment]
@moreaupascal56 Thanks again for identifying the issue areas! I talked with the team, and we are thinking to update the alias you identified in the [get_contact_columns() macro](https://github.com/fivetran/dbt_hubspot_source/blob/main/macros/get_contact_columns.sql) to be `create_date`. This way we're staying closer to the source naming, and you could still utilize the `property_created_at` field if you wish. We didn't want to remove user custom fields just because of the way we built the package. What are your thoughts?

**Comment by fivetran-catfritz** [comment]
Thanks @moreaupascal56! We plan to bring this into the next update for this package. We'll also let you know when we have a better sense of the timing.

**Comment by moreaupascal56** [comment]
Sounds great, thanks for the update!

Le mar. 17 oct. 2023, 20:29, fivetran-catfritz ***@***.***> a
écrit :

**Comment by fivetran-jamie** [comment]
this fix is in the latest [release](https://github.com/fivetran/dbt_hubspot_source/releases/tag/v0.13.0) of the package! 

if you're using the transform package, [v0.14.0](https://github.com/fivetran/dbt_hubspot/releases/tag/v0.14.0) will include this change

**Comment by moreaupascal56** [comment]
hi there,

Looks good I am not able to test on prod rn because I switched jobs but this will help the team for sure :) 
Thanks a lot and have a great day ! See you!!

Pascal
