### ISSUE TITLE
[Feature] Support for new association type composite keys

### ISSUE THREAD

**Issue by reubster** [fivetran/dbt_hubspot_source#131]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Following the [breaking changes](https://get.fivetran.com/index.php/email/emailWebview?email=MzUzLVVUQi00NDQAAAGV4O1156TGACfBzXKpJWmFSIPPxC-VzU5n9qbNmTL6jfoN__K18nk7M8WdRedAWLn0WGU4YIxRwy6fHkmjjHXIL_DvQhzb6fDwoQ) to the Hubspot API's and ingestion, the related objects in hubspot source need updating to;
- add the Category column
- update data uniqueness tests to check to include category in the test columns

### How would you implement this feature?

Since the change was introduced, we now have duplicate type id's in ASSOCIATION_TYPE

 | ID | NAME | CATEGORY | LABEL | FROM_OBJECT_TYPE | TO_OBJECT_TYPE | _FIVETRAN_DELETED | _FIVETRAN_SYNCED |
 | -- | ---- | -------- | ----- | ---------------- | -------------- | ----------------- | ---------------- |
 | 3 | day_to_day_contact | USER_DEFINED | Day to Day Contact | deal | contact | false | 2024-11-01 12:11:20.616000000 +00:00 |
 | 1 | onboarding_contact | USER_DEFINED | Onboarding Contact | deal | contact | false | 2024-11-01 12:11:20.616000000 +00:00 |
 | 1 | contact_to_company | HUBSPOT_DEFINED | Primary | contact | company | false | 2024-11-01 12:11:20.989000000 +00:00      |
 | 3 | day_to_day_contact | HUBSPOT_DEFINED |  | deal | contact | false | 2024-11-01 12:11:20.616000000 +00:00                |

### Describe alternatives you've considered

We've currently disabled unit tests for hubspot_source and hubspot, but this is just temporary to ensure our pipelines complete. 

Remove custom relationships in Hubspot - not acceptable to users

Fork dbt_hubspot_source and update - would very much prefer to keep using it 

### Are you interested in contributing this feature?

- [ ] Yes.
- [X] Yes, but I will need assistance.
- [ ] No.

**Comment by fivetran-reneeli** [comment]
Hi @reubster  thanks for raising this! We have been made aware of this connector update and are actively working on changes to this package currently. 

I saw you checked that you were interested in contributing! I will have a PR and branch opened in the coming days; it would be super helpful if you were open to testing that branch!

**Comment by fivetran-reneeli** [comment]
Hi @reubster! Here is the branch I created that hopefully addresses this test failure. Let me know once you get a chance to run it:

branch: `bugfix/category_add`

```
packages.yml:

  - git: https://github.com/fivetran/dbt_hubspot.git
    revision: bugfix/category_add
    warn-unpinned: false

**Comment by fivetran-reneeli** [comment]
Thanks @reubster for working with us! This has been merged into the main branch.
