### ISSUE TITLE
deal_adapter and contact_adapter are not created

### ISSUE THREAD

**Issue by gmontanola** [fivetran/dbt_hubspot_source#24]
Hi there folks,

My hubspot schema is not `hubspot`, but I've changed it on `dbt_project.yml`. But some models like:
* stg_hubspot__deal_adapter
* stg_hubspot__contact_adapter

Are still using `hubspot` as schema. Other models are just fine (but those are the base for plenty of other models).

### Examples of compiled SQL
_contact_adapter_
![image](https://user-images.githubusercontent.com/35972814/100147317-f74ef700-2e79-11eb-9d25-51d0b501fbbd.png)
_deal_pipeline_
![image](https://user-images.githubusercontent.com/35972814/100147350-033ab900-2e7a-11eb-8aba-f060e3b5f279.png)

### Extra info
**`dbt` on 0.18.0 and Redshift as my warehouse.**

**Comment by DylanBaker** [comment]
Hey @gmontanola. Thanks for sharing this. Would you be able to share which version of the package you're using and what your the relevant bit of your `dbt_project.yml` looks like?

**Comment by gmontanola** [comment]
> Hey @gmontanola. Thanks for sharing this. Would you be able to share which version of the package you're using and what your the relevant bit of your `dbt_project.yml` looks like?

Hi there Dylan! I had something like this:

```  hubspot_source:
    hubspot_schema: raw_hubspot
    hubspot_marketing_enabled: false
    hubspot_email_event_enabled: false
    hubspot_company_enabled: false
    hubspot_engagement_enabled: false
    hubspot_engagement_contact_enabled: false
    hubspot_engagement_company_enabled: false
    hubspot_engagement_deal_enabled: false
    hubspot_engagement_calls_enabled: false
    hubspot_engagement_emails_enabled: false
    hubspot_engagement_meetings_enabled: false
    hubspot_engagement_notes_enabled: false
    hubspot_engagement_tasks_enabled: false
```
And package `0.2.0`. I did not test without disabling model. I can't test it today, but I think it's worth a shot.

Thanks for replying :)

**Comment by fivetran-joemarkiewicz** [comment]
@gmontanola did the previously suggested solution allow you to write your HubSpot models to the correct schema? 

The upgrade to v0.2.0 did remove the two models you referenced that failed and I imagine this in turn allows your runs to succeed. As such, we will close this issue as it seems the issue was resolved. Please feel free to open an issue if the problem still persists.
