### ISSUE TITLE
No row returned by stg_hubspot__deal_pipeline_stage

### ISSUE THREAD

**Issue by pelletierjf** [fivetran/dbt_hubspot_source#4]
I'm using the package and I have an issue with stg_hubspot__deal_pipeline_stage.sql.

The code says:
`where _fivetran_deleted is null`

In my case, I have no row with null values. Only true/false. Therefore no row is returned. So you should check for false values as well.

**Comment by fivetran-jamie** [comment]
hey there - thanks for surfacing this, and apologies for the wait! this should be solved by the most recent release of the package, which now filters on `where not coalesce(_fivetran_deleted, false)` 😄
