### ISSUE TITLE
Need a default to include all columns as passthrough (previous behavor)

### ISSUE THREAD

**Issue by khookguy** [fivetran/dbt_hubspot_source#44]
**Are you a Fivetran customer?** 
Mark Hansen
Consultant
Edcurs

**Is your feature request related to a problem? Please describe.**
I was using the feature that ALL columns got passed through and cleaned up ('property_' removed).  Now, I have to create passthroughs for potentially hundreds of columns.  

**Describe the solution you'd like**
Provide a variable setting that can bring back the old behavior and include All columns automatically as passthroughs.  Something like `passthrough_all_columns = true`

**Describe alternatives you've considered**
Entering every single column as a name/alias pair in dbt_project.yml.  Barf!

**Additional context**

**Please indicate the level of urgency and business impact of this request** 
This upgrade broke our data warehouse and all dashboards. So, yes, it is urgent.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ X] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @khookguy This is a great idea and a feature that makes complete sense to add. I agree that customers who want to use every `property_` field would not appreciate painstakingly adding each and every field to the variable. I will add this feature request to our next SPRINT (starting mid next week) and will respond back here once we have assigned the task and begun work on it.

Thanks again for requesting this feature!

**Comment by khookguy** [comment]
Great! Thanks very much. If you need someone to test, I'm happy to.

**Comment by fivetran-jamie** [comment]
hey @khookguy -- what are your thoughts on having one blanket boolean-variable to pass through all columns in the affected tables (`deal`, `contact`, `company`, and `ticket` if you have it) vs 4 distinct boolean variables for the 4 different source tables? in your case, are you looking to just pass everything through, or are you thinking about specific tables? 

in [this PR](https://github.com/fivetran/dbt_hubspot_source/pull/48) I've just gone with the 1 `hubspot__pass_through_all_columns` variable instead of `hubspot__deal_pass_through_all_columns`, `hubspot__company_pass_through_all_columns`, etc...

**Comment by khookguy** [comment]
Hi @fivetran-jamie -- that sound good to me. We just want to be able to switch on the old behavior of having all the columns. We don't need the finer grain control at the table level.  Thanks!

**Comment by fivetran-jamie** [comment]
great! just pushed a [release](https://github.com/fivetran/dbt_hubspot_source/releases/tag/v0.4.1) incorporating this change. v0.4.1 should be up on dbt hub in about 20 minutes!

**Comment by fivetran-jamie** [comment]
this release is live on the hub!
