### ISSUE TITLE
Ticket models are not created

### ISSUE THREAD

**Issue by moseleyi** [fivetran/dbt_hubspot_source#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Company, Deal, Email, Engagement, and Owner staging tables are created fine but the Ticket tables are missing. Do they have to be enabled specifically?

### Expected behavior

Stg views defined in dbt_project.yml are available:
```
    ticket_company: "{{ source('hubspot','ticket_company') }}"
    ticket_contact: "{{ source('hubspot','ticket_contact') }}"
    ticket_deal: "{{ source('hubspot','ticket_deal') }}"
    ticket_engagement: "{{ source('hubspot','ticket_engagement') }}"
    ticket_pipeline: "{{ source('hubspot','ticket_pipeline') }}"
    ticket_pipeline_stage: "{{ source('hubspot','ticket_pipeline_stage') }}"
    ticket_property_history: "{{ source('hubspot','ticket_property_history') }}"
    ticket: "{{ source('hubspot','ticket') }}"
```

### dbt Project configurations

vars:
  hubspot_source:
    hubspot_database: FIVETRAN
    hubspot_schema: hubspot
  hubspot_email_event_print_enabled: false
  hubspot_email_event_forward_enabled: false
  hubspot_contact_merge_audit_enabled: true
  hubspot__pass_through_all_columns: true

### Package versions

packages:
  - package: dbt-labs/audit_helper
    version: 0.5.0
  - package: fivetran/hubspot
    version: [">=0.5.0", "<0.6.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.2

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @moseleyi thanks so much for opening this issue!

Luckily there is a quick fix for you to get the ticket models created in your next run. You can simple set the `hubspot_service_enabled` variable to be `true` (it is `false` by default).
```yml
vars:
   hubspot_service_enabled: true
```

While this is a quick fix, we did not do a good job documenting in the README that this variable is used for the ticket models. I noticed you are open to creating a PR! This would be a great documentation update PR if you are willing to tackle it. I would recommend we simply adjust our wording in the [Disable Models](https://github.com/fivetran/dbt_hubspot_source#disabling-models) section to explicitly state that this variable is used for the ticket models. Similarly, we would want to make the same adjustment in our [dbt_hubspot](https://github.com/fivetran/dbt_hubspot) package to be consistent with the documentation.

Let me know if you would be interested in addressing this PR. Otherwise, our team will be able to address this in our next sprint. Additionally, please let me know if setting the variable fixes your initial problem, if not we will want to look more into that 😄

**Comment by moseleyi** [comment]
Hi, 

I added `hubspot_service_enabled: true` like you suggested but now I'm getting this error:

```
06:42:07  Database Error in model stg_hubspot__ticket_deal_tmp (models/tmp/stg_hubspot__ticket_deal_tmp.sql)
06:42:07    002003 (42S02): SQL compilation error:
06:42:07    Object 'FIVETRAN.HUBSPOT.TICKET_DEAL' does not exist or not authorized.
06:42:07    compiled SQL at target/run/hubspot_source/models/tmp/stg_hubspot__ticket_deal_tmp.sql
```

I'm guessing it's because we never used the connection between tickets and deals but it shouldn't stop  the package from creating basic ticket models, that are independent of Deals, should it?

**Comment by fivetran-jamie** [comment]
Hi @moseleyi -- can you confirm that the `ticket_deal` table doesn't exist in your warehouse? if that's indeed the case, I am thinking we should introduce a `hubspot_ticket_deal_enabled` variable to disable its corresponding models

**Comment by moseleyi** [comment]
Fivetran does have it selected but the table isn't built, which I'm guessing suggests that it hasn't been used in Hubspot. Probably because when we used tickets, we never used to join them with Deals. 
![image](https://user-images.githubusercontent.com/16131590/185352992-6764d385-ffed-4658-9c82-e6f9bc71d438.png)

**Comment by fivetran-jamie** [comment]
hey @moseleyi i've added a `hubspot_ticket_deal_enabled` variable that's false by default, this should let you just bypass these models since you don't have the `ticket_deal` source table (which most people don't)

if you'd like to try it out:
```yml
packages:
  - git: https://github.com/fivetran/dbt_hubspot_source.git
    revision: feature/disable-ticket-deal
    warn-unpinned: false
```

**Comment by moseleyi** [comment]
I added the package but still getting an error:
![image](https://user-images.githubusercontent.com/16131590/185558234-a7b0e08c-c52f-49a2-b073-40c6ad2e9f32.png)


![image](https://user-images.githubusercontent.com/16131590/185558271-75ac3347-f82f-4ea4-8313-a831b78b7ffb.png)

**Comment by moseleyi** [comment]
hmm is this not going to clash with the fivetran/hubspot package since it already has a hubspot_source dependency?

**Comment by fivetran-jamie** [comment]
ah yeah -- lemme change the hubspot `bugfix/deleted-stages` branch to refer to this `feature/disable-ticket-deal` branch of the source package, so you can test both with that one package reference

**Comment by fivetran-jamie** [comment]
ok the transform package should reference this branch, so you can remove the `dbt_hubspot_source` package reference

**Comment by moseleyi** [comment]
I ran the dbt deps

![image](https://user-images.githubusercontent.com/16131590/185858921-d7cec038-269e-4406-b577-75f5d85dbbcc.png)

and I have this:

```
  hubspot_service_enabled: true
  hubspot_ticket_deal_enabled: false
```

And the ticket deal doesn't show an error anymore. Other ticket views are created but the `ticket_deal` is ommitted as expected

**Comment by fivetran-jamie** [comment]
like no ticket-related staging models are showing up? that would mean it's not capturing that you have the `hubspot_service_enabled` var set to true 🤔

**Comment by moseleyi** [comment]
STaging views are created:

![image](https://user-images.githubusercontent.com/16131590/186091704-71723285-3eab-4e23-acf0-e61aef7bb5d6.png)

but no actual ticket-related models

**Comment by fivetran-jamie** [comment]
ah by `ticket-related materialised tables` do you mean transform models? if so, the transform package actually doesn't do anything with tickets -- the source package just creates staging models for them

**Comment by fivetran-jamie** [comment]
or rather do you mean you'd want these views materialized as tables?

**Comment by moseleyi** [comment]
Ahh okay, I thought tables would also be built automatically like for others but I see it's not in the hubspot package

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as it has since been resolved.
