### ISSUE TITLE
[Bug] Staging .yml docs missing column descriptions

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_hubspot_source#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In doing a spot check of the docs, some model column descriptions are missing or appear not to match the data type. See [stg_hubspot__company](https://fivetran.github.io/dbt_hubspot_source/#!/model/model.hubspot_source.stg_hubspot__company) or [stg_hubspot__contact_list](https://fivetran.github.io/dbt_hubspot_source/#!/model/model.hubspot_source.stg_hubspot__contact_list) as examples.

Suggest to audit and update table descriptions. 

### Expected behavior

All columns should have a correct description. 

### dbt Project configurations

n/a

### Package versions

0.6.3

### What database are you using dbt with?

bigquery

### dbt Version

n/a

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as PR #84 and #88 addressed the original bug identified.
