### ISSUE TITLE
[Feature] Exclude foreign key references for deleted records

### ISSUE THREAD

**Issue by kylemcnair** [fivetran/dbt_hubspot_source#87]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

**Problem**

Deleted records for `deal`, `company`, and `ticket` are excluded from their respective models, each with a final select of:
```
select *
from fields
where not coalesce(is_deleted, false)
```

However, ALL keys for these entities can appear in other models. The exclusion of deleted records isn't accounted for in other models, and can result in orphaned records.

For example, we had two companies merged into a single company, resulting in a deleted company record. Both companies shared the same deal_id. The deals_company table contains a record for each company, but only one company has a corresponding record in the `hubspot_company` table. This relationship resulted in a failing uniqueness test.

<br>

**Solution**

To maintain referential integrity, references to deleted entities should be removed from all models. ie, if a deleted company is excluded from the core `company` model, that deleted company_id should not appear in any other models.

This could be implemented via a macro that looks for foreign keys referencing any of the three models with deletes.

Some version of:
 * if source_columns in company_id
 * append "company id in (select company_id from stg_company) "

If this general approach makes sense, I can flesh out more specifics with the macro.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

[original post in the #tools-fivetran channel in the dbt Slack](https://getdbt.slack.com/archives/C01D1R2JLLA/p1662738393453809)

**Comment by fivetran-joemarkiewicz** [comment]
Hi @kylemcnair thanks so much for creating this feature request. I see the issue you are outlining and appreciate you thinking through a series of solutions.

My team and I are going to think through this a bit more and determine possible avenues forward here. Be sure to watch this thread as we will likely come back with follow up questions as we dig further into this.

**Comment by fivetran-jamie** [comment]
@kylemcnair what are thoughts on your solution vs **not** deleting soft-deleted entities and persisting the `is_entity_deleted` columns downstream? 

would you rather have no reporting on these deleted entities at all, or _complete_ reporting with this is-deleted flag to pick and choose places to ignore them?

**Comment by kylemcnair** [comment]
> @kylemcnair what are thoughts on your solution vs **not** deleting soft-deleted entities and persisting the `is_entity_deleted` columns downstream?
> 
> would you rather have no reporting on these deleted entities at all, or _complete_ reporting with this is-deleted flag to pick and choose places to ignore them?

@fivetran-jamie I like your proposed solution - it leaves a more complete dataset and would be much simpler to implement than an elaborate macro.

**Comment by kylemcnair** [comment]
@fivetran-jamie should I run with this and open a PR? more than happy to, just lmk

**Comment by fivetran-joemarkiewicz** [comment]
Closing out this feature request as the above linked merged PRs address the request.
